version: '3.8'

services:
  # MongoDB Database for Development
  mongodb-dev:
    image: mongo:6.0
    container_name: nova-meet-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: nova_meet_dev
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - nova-meet-dev-network

  # Redis for Development
  redis-dev:
    image: redis:7-alpine
    container_name: nova-meet-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - nova-meet-dev-network

volumes:
  mongodb_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  nova-meet-dev-network:
    driver: bridge
